import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/react"; // Example import, adjust as needed

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ivene 1.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          {children}
          <Analytics debug={false}/> {/* Add Analytics here */}
        </body>
      </html>
    </ClerkProvider>
  );
}
